In [40]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, Normalizer, MinMaxScaler, MaxAbsScaler, RobustScaler

#### Q1 - Standardization

In [13]:
df = pd.DataFrame({
    'height': [50, 52, 38, 44, 36, 48, 42, 40, 55, 30],
    'weight': [140, 130, 135, 145, 162, 175, 140, 155, 158, 165],
})

ss = StandardScaler()
df[['height_scaled','weight_scaled']] = ss.fit_transform(df)

print('Before')
print(f'Height Mean: {df['height'].mean().round(2)}, Weight: {df['weight'].mean().round(2)}')
print(f'Height Std: {df['height'].std().round(2)}, Weight: {df['weight'].std().round(2)}')

print('After')
print(f'Height Mean: {df['height_scaled'].mean().round(2)}, Weight: {df['weight_scaled'].mean().round(2)}')
print(f'Height Std: {df['height_scaled'].std().round(2)}, Weight: {df['weight_scaled'].std().round(2)}')

Before
Height Mean: 43.5, Weight: 150.5
Height Std: 7.82, Weight: 14.65
After
Height Mean: 0.0, Weight: 0.0
Height Std: 1.05, Weight: 1.05

#### Q2 - Normalization

In [32]:
df = pd.DataFrame({
    'user':     ['Aarav','Priya','Ravi','Sneha','Karan'],
    'biryani':  [10, 2, 0, 8, 5],
    'pizza':    [2, 8, 1, 3, 6],
    'dosa':     [5, 1, 9, 2, 4],
    'burger':   [1, 5, 2, 7, 3],
})
cols = ['biryani','pizza','dosa','burger']
l2 = Normalizer(norm='l2')

df_l2 = df.copy()
df_l2[cols] = l2.fit_transform(df[cols])

print('Normalized: ')
display(df_l2.round(2))

print('Verify:')
row_norms = np.sqrt((df_l2[cols]**2).sum(axis=1))
print(row_norms.values)

Normalized:

    user  biryani  pizza  dosa  burger
0  Aarav     0.88   0.18  0.44    0.09
1  Priya     0.21   0.83  0.10    0.52
2   Ravi     0.00   0.11  0.97    0.22
3  Sneha     0.71   0.27  0.18    0.62
4  Karan     0.54   0.65  0.43    0.32

Verify:
[1. 1. 1. 1. 1.]

#### Q3 - Min-Max Scaling

In [41]:
np.random.seed(9009)
df = pd.DataFrame({
    'salary' : np.random.randint(20000,100000,20)
})

mm = MinMaxScaler()
df_mm = pd.DataFrame(mm.fit_transform(df), columns=df.columns)

print('MinMax Scaled: ')
display(df_mm.round(2).head())

MinMax Scaled:

   salary
0    0.89
1    0.47
2    0.01
3    0.44
4    0.42

#### Q4 - Max-Abs Scaling

In [44]:
df = pd.DataFrame({
    'balance' : np.random.randint(-20000,20000,20)
})

ma = MaxAbsScaler()
df_ma = pd.DataFrame(ma.fit_transform(df), columns=df.columns)

print('MaxAbs Scaled: ')
display(df_ma.round(2).head())

MaxAbs Scaled:

   balance
0    -0.53
1     0.74
2    -0.11
3     0.05
4    -0.52

#### Q5 - Robust Sacling

In [47]:
df = pd.DataFrame({
    'income_lakh':  [8, 12, 6, 15, 9, 11, 10, 14, 0.5, 200]
})

rs = RobustScaler()
df_rs = pd.DataFrame(rs.fit_transform(df), columns=df.columns)
print('Robust Scaled: ')
display(df_rs.round(2))

Robust Scaled:

   income_lakh
0        -0.48
1         0.29
2        -0.86
3         0.86
4        -0.29
5         0.10
6        -0.10
7         0.67
8        -1.90
9        36.10