In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, OneHotEncoder

#### Q1 - Data Ordinal Encoding

In [3]:
# Created dataset

df = pd.DataFrame({
    'applicant': ['Aarav', 'Priya', 'Ravi', 'Sneha', 'Karan',
                  'Divya', 'Mohit', 'Ananya'],
    'education': ['Graduate',      'Post-Graduate', 'School',
                  'Graduate',      'Post-Graduate', 'School',
                  'Graduate',      'Post-Graduate'],

})
display(df)

  applicant      education
0     Aarav       Graduate
1     Priya  Post-Graduate
2      Ravi         School
3     Sneha       Graduate
4     Karan  Post-Graduate
5     Divya         School
6     Mohit       Graduate
7    Ananya  Post-Graduate

In [13]:
# Encode

ordenc = OrdinalEncoder(
    categories=[['School', 'Graduate', 'Post-Graduate']]
)

df['education_enc'] = ordenc.fit_transform(df[['education']]).astype(int)
display(df)

  applicant      education  education_enc
0     Aarav       Graduate              1
1     Priya  Post-Graduate              2
2      Ravi         School              0
3     Sneha       Graduate              1
4     Karan  Post-Graduate              2
5     Divya         School              0
6     Mohit       Graduate              1
7    Ananya  Post-Graduate              2

#### Q2 - Label Encoding

In [14]:
# Create dataset

df = pd.DataFrame({
    'driver_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'city':      ['Mumbai', 'Delhi', 'Pune', 'Mumbai',
                  'Chennai', 'Delhi', 'Pune', 'Chennai'],
})
display(df)

   driver_id     city
0          1   Mumbai
1          2    Delhi
2          3     Pune
3          4   Mumbai
4          5  Chennai
5          6    Delhi
6          7     Pune
7          8  Chennai

In [17]:
# Encoding

labenc = LabelEncoder()

df['city_enc'] = labenc.fit_transform(df['city'])+1
display(df)

   driver_id     city  city_enc
0          1   Mumbai         3
1          2    Delhi         2
2          3     Pune         4
3          4   Mumbai         3
4          5  Chennai         1
5          6    Delhi         2
6          7     Pune         4
7          8  Chennai         1

#### Q3 - One-Hot Encoding

In [19]:
# Created dataset

df = pd.DataFrame({
    'emp_id':  [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    'department':   ['HR',       'IT',     'Finance',     'Sales',
                  'IT',      'IT',      'Finance',     'Sales'],

})
display(df)

   emp_id department
0    1001         HR
1    1002         IT
2    1003    Finance
3    1004      Sales
4    1005         IT
5    1006         IT
6    1007    Finance
7    1008      Sales

In [29]:
# Encoding using OneHotEncoder

ohenc = OneHotEncoder(
    drop='first',
    handle_unknown='ignore',
    sparse_output=False
)

col = ['department']
enc_array = ohenc.fit_transform(df[col])

col_names = ohenc.get_feature_names_out(col)

df_ohe = pd.DataFrame(enc_array, columns=col_names)
display(df_ohe)

   department_HR  department_IT  department_Sales
0            1.0            0.0               0.0
1            0.0            1.0               0.0
2            0.0            0.0               0.0
3            0.0            0.0               1.0
4            0.0            1.0               0.0
5            0.0            1.0               0.0
6            0.0            0.0               0.0
7            0.0            0.0               1.0

In [30]:
# Encoding using pd.get_dummies()

df_pd = pd.get_dummies(df['department'], drop_first=True, prefix='department')
display(df_pd)

   department_HR  department_IT  department_Sales
0           True          False             False
1          False           True             False
2          False          False             False
3          False          False              True
4          False           True             False
5          False           True             False
6          False          False             False
7          False          False              True