In [1]:
import pandas as pd
import seaborn as sns
import torch

#### Q1 - Planning a Data Science Project

In [2]:
# Dataset

titanic = pd.DataFrame(sns.load_dataset('titanic'))
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
# Project Goal

' Project Goal is to find which type of group or individual had more chance to survive. '

' Project Goal is to find which type of group or individual had more chance to survive. '

In [4]:
# Data Science Pipeline

pipeline = {
    'Step 1': 'Data Collection',
    'Step 2': 'Data Cleaning',
    'Step 3': 'EDA',
    'Step 4': 'Analysis & Modeling',
    'Step 5': 'Communicate',
}

for i,j in pipeline.items():
    print(f'{i}: {j}')

Step 1: Data Collection
Step 2: Data Cleaning
Step 3: EDA
Step 4: Analysis & Modeling
Step 5: Communicate

#### Q2 - Framing a Machine Learning Problem

In [5]:
# Dataset

titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
# Define Features and Target

' What is the input (features)? -> sex, age, pclass, deck, alone, who '
' What is the output (target)? ->  survived '
' What kind of ML problem is this? -> Classification '

' What kind of ML problem is this? -> Classification '

In [7]:
# Problem Structure

structure = {
    'Dataset': 'Titanic',
    'Features': ['Sex', 'Age', 'PClass', 'Deck', 'Alone', 'Who'],
    'Target': 'Survived',
    'ML_Type': 'Classification'
}

for i,j in structure.items():
    print(f'{i}: {j}')

Dataset: Titanic
Features: ['Sex', 'Age', 'PClass', 'Deck', 'Alone', 'Who']
Target: Survived
ML_Type: Classification

#### Q3 - Tensors

In [8]:
# Pandas & Torch

pd_scalar = pd.Series([1])
pd_vector = pd.Series([1, 2, 3])
pd_matrix = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



scalar = torch.tensor(1)
vector = torch.tensor([1,2,3,4,5])
matrix = torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
tensor3D = torch.rand(3,4,4)

print('Pandas')
print(f'Value: \n{pd_scalar}')
print(f'Dimension: {pd_scalar.ndim}, Shape: {pd_scalar.shape}\n')

print(f'Value: \n{pd_vector}')
print(f'Dimension: {pd_vector.ndim}, Shape: {pd_vector.shape}\n')

print(f'Value: \n{pd_matrix}')
print(f'Dimension: {pd_matrix.ndim}, Shape: {pd_matrix.shape}\n')


print('Tensor')
print(f'Value: \n{scalar}')
print(f'Dimension: {scalar.ndim}, Shape: {scalar.shape}\n')

print(f'Value: \n{vector}')
print(f'Dimension: {vector.ndim}, Shape: {vector.shape}\n')

print(f'Value: \n{matrix}')
print(f'Dimension: {matrix.ndim}, Shape: {matrix.shape}\n')

print(f'Value: \n{tensor3D}')
print(f'Dimension: {tensor3D.ndim}, Shape: {tensor3D.shape}\n')

Pandas
Value:
0    1
dtype: int64
Dimension: 1, Shape: (1,)

Value:
0    1
1    2
2    3
dtype: int64
Dimension: 1, Shape: (3,)

Value:
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
Dimension: 2, Shape: (3, 3)

Tensor
Value:
1
Dimension: 0, Shape: torch.Size([])

Value:
tensor([1, 2, 3, 4, 5])
Dimension: 1, Shape: torch.Size([5])

Value:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Dimension: 2, Shape: torch.Size([3, 3])

Value:
tensor([[[0.9264, 0.8706, 0.8986, 0.2522],
         [0.2497, 0.4164, 0.5256, 0.3810],
         [0.7543, 0.6593, 0.3225, 0.7193],
         [0.3562, 0.1494, 0.8343, 0.8139]],

        [[0.6684, 0.8643, 0.2097, 0.4274],
         [0.1605, 0.5996, 0.0966, 0.0323],
         [0.8804, 0.8946, 0.9367, 0.9652],
         [0.7857, 0.6029, 0.4981, 0.4848]],

        [[0.1416, 0.8648, 0.7291, 0.8331],
         [0.1422, 0.1207, 0.1366, 0.9334],
         [0.5130, 0.0458, 0.5413, 0.9292],
         [0.9843, 0.5225, 0.3874, 0.8262]]])
Dimension: 3, Shape: torch.Size([3, 4, 4])

#### Q4 - Tensors

In [9]:
# Generate (3,3,3)

random = torch.rand(3,3,3)
print(f'Original Shape: {random.shape}')

Original Shape: torch.Size([3, 3, 3])

In [10]:
# Perform

random_re = random.reshape(9,3)
print(f'Reshape: {random_re.shape}')

print(f'Slicing: {random_re[:2]}')

x = torch.rand(2,4)
y = torch.rand(4,5)

multi = x.matmul(y)

multi

Reshape: torch.Size([9, 3])
Slicing: tensor([[0.7190, 0.2360, 0.0655],
        [0.4186, 0.5461, 0.6984]])

tensor([[0.9551, 0.4581, 0.8100, 1.4280, 1.2137],
        [1.8318, 0.5839, 1.4125, 2.5869, 2.3024]])

In [17]:
# Broadcasting

x = torch.rand(3,1)
print(f'X: \n{x}')

y = torch.rand(3,3)
print(f'Y: \n{y}')

print(f'Sum of X + Y: \n{x + y}')

X:
tensor([[0.7249],
        [0.7109],
        [0.1040]])
Y:
tensor([[0.6864, 0.5522, 0.9443],
        [0.3227, 0.5370, 0.8843],
        [0.9911, 0.5987, 0.7116]])
Sum of X + Y:
tensor([[1.4113, 1.2772, 1.6692],
        [1.0336, 1.2479, 1.5952],
        [1.0951, 0.7027, 0.8156]])